ktor:
    application:
        modules:
            - multek.com.ApplicationKt.main
    deployment:
        port: 8080
    development: true
postgres:
    url: "jdbc:postgresql://localhost:5432/todolist"
    user: postgres
    password: postgres

